spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_project_db
    username: postgres
    password: theflanders
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false